# Generated by Django 6.0.4 on 2026-04-20 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_appointments', models.PositiveIntegerField(default=0)),
                ('confirmed_appointments', models.PositiveIntegerField(default=0)),
                ('cancelled_appointments', models.PositiveIntegerField(default=0)),
                ('new_patients', models.PositiveIntegerField(default=0)),
                ('new_doctors', models.PositiveIntegerField(default=0)),
                ('new_hospitals', models.PositiveIntegerField(default=0)),
                ('pharmacy_orders', models.PositiveIntegerField(default=0)),
                ('pharmacy_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('booking_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mf_daily_snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HospitalKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('bed_occupancy_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('icu_occupancy_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('appointments_count', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_wait_minutes', models.PositiveIntegerField(default=0)),
                ('patient_satisfaction', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'mf_hospital_kpis',
                'ordering': ['-date'],
                'unique_together': {('hospital', 'date')},
            },
        ),
    ]
